### ISSUE TITLE
Email or password is incorrect.

### ISSUE THREAD

**Issue by ElJoker63** [ThatNotEasy/Widevine-KSKEY#10]
netflix.py", line 765, in load_playlist     
    raise LoginError(manifest.get("error", {}).get("display", error))
modules.errors.LoginError: Email or password is incorrect.

**Comment by Khysnik** [comment]
#6 He says that only Chrome CDMs are supported, but doesn't elaborate past that. We're stuck until he fixes it.

**Comment by Ap0dexMe0** [comment]
> #6 He says that only Chrome CDMs are supported, but doesn't elaborate past that. We're stuck until he fixes it.

thanks! still in construction
