### ISSUE TITLE
Dependencies conflict in requirements.txt

### ISSUE THREAD

**Issue by stickyfin** [ThatNotEasy/Widevine-KSKEY#13]
I'm trying to install pip requirements.txt and stumbled upon the following issues:
> ERROR: Cannot install -r requirements.txt (line 18), -r requirements.txt (line 27), -r requirements.txt (line 28), -r requirements.txt (line 53), -r requirements.txt (line 60) and requests==2.32.3 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested requests==2.32.3
>     cloudscraper 1.2.71 depends on requests>=2.9.2
>     downloadkit 2.0.2 depends on requests
>     drissionpage 4.0.5.6 depends on requests
>     jsorlie-pymsl 1.3 depends on requests
>     m3u8dl 0.5.2 depends on requests==2.26.0
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

I tried to play around with the _requests_ version but still not working.

I'm using python virtual environment: python3 -m venv env , source env/bin/activate

More details on the machine used:
OS: Ubuntu 24.04 LTS
Python version: Python 3.12.3
Pip version: pip 24.0

**Comment by Ap0dexMe0** [comment]
SOLVE!

**Comment by shoval6** [comment]
ERROR: Cannot install -r requirements.txt (line 26), -r requirements.txt (line 27), -r requirements.txt (line 52), -r requirements.txt (line 59), -r requirements.txt (line 93), -r requirements.txt (line 99) and requests because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests
    downloadkit 2.0.4 depends on requests
    drissionpage 0.8.1 depends on requests
    jsorlie-pymsl 1.3 depends on requests
    m3u8dl 0.1.1 depends on requests==2.24.0
    pymsl 1.0 depends on requests
    pywidevine 1.8.0 depends on requests<3.0.0 and >=2.31.0
    The user requested requests
    downloadkit 2.0.4 depends on requests
    drissionpage 0.8.1 depends on requests
    jsorlie-pymsl 1.3 depends on requests
    m3u8dl 0.1.1 depends on requests==2.24.0
    pymsl 1.0 depends on requests
    pywidevine 1.7.0 depends on requests<3.0.0 and >=2.31.0
    The user requested (constraint) requests<2.27.0,>=2.24.0
    
I have the same problem. How did you solve it ? @stickyfin
