### ISSUE TITLE
Service videotron Android CDM or Chrom CDM ?

### ISSUE THREAD

**Issue by whip28** [ThatNotEasy/Widevine-KSKEY#16]
Videotron is you just Android L1 and Chrome CDM?. Or does a CDM L3 Android work too?

![Capture d’écran 2024-10-03 163910](https://github.com/user-attachments/assets/23e9e08c-fad2-495d-818d-ac9957cd87fc)
![Capture d’écran 2024-10-03 190320](https://github.com/user-attachments/assets/390fcb5e-3f07-46d9-9051-de2db1c9fc95)

**Comment by Ap0dexMe0** [comment]
L3 work too.
