### ISSUE TITLE
Getting an error in key process

### ISSUE THREAD

**Issue by shoval6** [ThatNotEasy/Widevine-KSKEY#20]
Hello , 

I'm trying to get the key , I'm running the command with License url and MPD url.
This is the following error :
![Screenshot_8](https://github.com/user-attachments/assets/46d830e3-50f6-455e-84d2-234d9cdf739b)

1. No KID found in manifest , is it necessary ?
2.  No .wvd files found in the directory - I understand that CDM is missing  , how to fix that ? 
I thought the script is taking care of that automatically.

Thank you for all.

**Comment by Ap0dexMe0** [comment]
> Hello ,
> 
> I'm trying to get the key , I'm running the command with License url and MPD url. This is the following error : ![Screenshot_8](https://private-user-images.githubusercontent.com/33618381/376699802-46d830e3-50f6-455e-84d2-234d9cdf739b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTQzNTUsIm5iZiI6MTcyOTAxNDA1NSwicGF0aCI6Ii8zMzYxODM4MS8zNzY2OTk4MDItNDZkODMwZTMtNTBmNi00NTVlLTg0ZDItMjM0ZDljZGY3MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE3NDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODRmYjg3Njc2OTk5Zjk3NjdlZmNlNjdhYjgxZGYyZGE2ZWVmOGExNzFiZTRjZDVjMGQwNGNiZjMxNTE0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xPKtje3mi85BT1D3ggwIOo8uxI4Ts9mg_B07IGAi6rk)
> 
> 1. No KID found in manifest , is it necessary ?
> 2. No .wvd files found in the directory - I understand that CDM is missing  , how to fix that ?
>    I thought the script is taking care of that automatically.
> 
> Thank you for all.

what are you trying to do? please read the repo description. create a ```device``` directory and put the wvd there
![{9CD89748-F12B-41C0-85EC-8CFAEA2671B2}](https://github.com/user-attachments/assets/407729bc-10c5-436c-a4ae-4ff1ecf3a96e)

**Comment by shoval6** [comment]
I'm sorry but all this things are new for me .
I have a video with DRM-protected content (MPD) from certain web (like netflix) , I wanna get the required key for decrypting it , before download.
So I put the manifest url and the license url , now I need you to explain me how to get the .wvd files.
You don't answer me about the KID.
I'll be glad if you make the things more clear.
Thank you for patience.

**Comment by sedansindie05** [comment]
if i had PSSH and License. How to use terminal command?

**Comment by Ap0dexMe0** [comment]
you both can read a new description update [here](https://github.com/ThatNotEasy/Widevine-KSKEY/blob/4406d6eeae3f36d8311a17270eaa4e9a9aadc965/README.md)
