### ISSUE TITLE
Adding filmin.es and ver.movistarplus.es services

### ISSUE THREAD

**Issue by balleno75** [ThatNotEasy/Widevine-KSKEY#7]
Hi, would you mind guiding me on how to add the filmin.es and ver.movistarplus.es services to your script?

Cookies, credentials, other necessary data, etc.

Thank you very much. Greetings.

**Comment by Ap0dexMe0** [comment]
dm credentials on telegram, i will adding that services: https://telegram.me/SurpriseMTFK
